### ISSUE TITLE
Can't save images

### ISSUE THREAD

**Issue by rmlmcfadden** [dfujim/bccd#3]
Saving an image from the interactive canvas fails with the following error: 

![Screenshot from 2023-09-21 12-42-11](https://github.com/dfujim/bccd/assets/60617588/ba39ed41-373d-4171-b756-df783d7565ed)

This was encountered while running:
- Python 3.11.5
- bccd 2.8.6

**Comment by dfujim** [comment]
Resolved in 417f1c8f3b558677b7f62725b825d0acba5aca96

Please update to v2.9.2

**Comment by dfujim** [comment]
Forgot to close
